### ISSUE TITLE
Design the sign in form

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v37-toucans-team-02#100]
**__Task Description__**
Design the sign in form

- [ ] do some research on ideas how other websites do that
- [ ] the form must aesthetically match the log in form
- [ ] present your idea on a group chat

**__Additional Considerations__**
.
