### ISSUE TITLE
Design the log in page

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v37-toucans-team-02#93]
**__Task Description__**
Put your vision into the more visible state. 

- [ ] do some research on how other websites do their log in page, get some inspiration
- [ ] create low fidelity frame and present it in the group chat
- [ ] decide on final design

**__Technical Considerations__**
.

**__Additional Considerations__**
.
